### ISSUE TITLE
Style and Theme of virtual labs on Open edX platform conveys a uniqueness relevant to Indian context.

### ISSUE THREAD

**Issue by travula** [vlead/edx#8] opened 2016-03-04 04:28 UTC

**Comment by travula** [comment] 2016-03-17 08:51
Takeaway from the review on 17/3/2016.
1. Footer and Header to match the current vlabs.ac.in landing page.
2. Start dates to be removed from each course tile.
3. Labs should replace Courses.
4. Color Theming ( match the current vlabs.ac.in)
5. All courses should be Anytime.
6. Consortium logos should be present like on https://www.edx.org/
7. lab tile outline specific for each institute/

**Comment by travula** [comment] 2016-03-17 08:53
@dinnu93

**Comment by dinnu93** [comment] 2016-03-18 07:45
More Items http://issues.vlabs.ac.in/issues/710#journal-3142-notes

**Comment by dinnu93** [comment] 2016-03-30 08:45
1. Front page is to be improved tiles and banner.
2. Use banner of vlabs.ac.in in edx website as it is.
3. Replace date with "Anytime" in the course tile.
4. About page of the course should link to external links for now.
5. Put the right license in course details page.
6. Feedback is to be added to the footer.
7. Studio does not have themes, we need to add themes to studio as well.
8. Institutes logo in the labs page. e.g. IIT Kanpur
9. Banner with all the universities is to be designed.

**Comment by travula** [comment] 2016-04-26 04:41
There are different entities which comes configured with edX by default. We have to customize it so that edX platform looks specific to Virtual-labs. Following are the entities/components which are to be customized -
1. Register page needs to be customized by adding image and text.
2. Need to replace email address with example.com domain.
3. Need to fix the activation email link, sent on registration.
4. Restricting a Student to login into studio and create/edit course.
5. Change the platform name in LMS and CMS.
6. Applying logo in LMS and CMS.
7. Removing extra labels on edX from studio and other page.
8. Terms and conditions page of Studio signup page.
9. Need to change the placeholders in LMS and CMS
10. Forgot password link in Studio signin page.
11. Footer and Header to match the current vlabs.ac.in landing page.
12. Start dates to be removed from each course tile.
13. Labs should replace Courses.
14. Color Theming ( match the current vlabs.ac.in)
15. All courses should be Anytime.
16. Consortium logos should be present like on https://www.edx.org/
17. lab tile outline specific for each institute
18. Changing url for social networks (facebook.com, twitter.com)
19. Changing account activation notification to a registered use.
20. Changing the body of activation mail sent to a user on registration.

**Comment by ashay-maheshwari** [comment] 2016-04-27 07:12
Fixed :+1: 
- 3.  **Activation link of registration email**\- https://github.com/vlead/port-labs-to-openedx/blob/develop/src/theming-customization/index.org#changing-site-namefixing-the-activation-email-link-which-comes-with-httplocalhost
- 4.  **Restricting a Student to login into studio and create/edit course** - https://github.com/vlead/port-labs-to-openedx/blob/develop/src/platform-installation/index.org#disable-course-creation-for-users-on-edx-studio
- 5.  **Change platform name in LMS and CMS** - https://github.com/vlead/port-labs-to-openedx/blob/develop/src/theming-customization/index.org#changing-platform-name-in-edx-lms-and-cms
- 6.  **Applying logo in LMS/CMS** - https://github.com/vlead/port-labs-to-openedx/blob/develop/src/theming-customization/index.org#changing-the-site-log-on-studio
- 21. **Adding/attaching external websites with edX** - https://github.com/vlead/port-labs-to-openedx/blob/develop/src/theming-customization/index.org#addingattaching-external-websites-with-edx
- 20. **Changing the body of activation mail sent to a user on registration** - https://github.com/vlead/port-labs-to-openedx/blob/develop/src/edx-customization.org#changing-the-body-of-activation-mail-sent-to-a-user-on-registration
- 7.  **Removing extra labels on edX from studio and other page** - https://github.com/vlead/port-labs-to-openedx/blob/develop/src/edx-customization.org#removing-extra-labels-on-edx-from-studio-and-other-pages
- 19. **Changing account activation notification to a registered user** -  https://github.com/vlead/port-labs-to-openedx/blob/develop/src/edx-customization.org#changing-account-activation-notification-to-a-registered-user
- 18. **Changing url for social networks (facebook.com, twitter.com)** -  https://github.com/vlead/port-labs-to-openedx/blob/develop/src/edx-customization.org#changing-url-for-social-networks-facebookcom-twittercom

**Comment by ashay-maheshwari** [comment] 2016-04-29 02:39
Components which cannot be customized with theming process will not be customized.
Editing source code for customization is not a proper and feasible way for customization.
As a result, components which can be customized using theming or changing configuration files are -

**Components which can be customized using Config files and theming**
- Need to replace email address with example.com domain.
- Need to fix the activation email link, sent on registration.
- Restricting a Student to login into studio and create/edit course.
- Change the platform name in LMS and CMS.
- Applying logo in LMS and CMS.
- Start dates to be removed from each course tile.
- All courses should be Anytime.
- Color Theming ( match the current vlabs.ac.in)
- Footer and Header to match the current vlabs.ac.in landing page.
- Forgot password link in Studio signin page.
- lab tile outline specific for each institute

**Components which cannot be customized using configuration files and theming**
- Register page needs to be customized by adding image and text.
- Removing extra labels on edX from studio and other page.
- Terms and conditions page of Studio signup page.
- Need to change the placeholders in LMS and CMS
- Forgot password link in Studio signin page.
- Changing url for social networks (facebook.com, twitter.com)
- Changing account activation notification to a registered use.
- Changing the body of activation mail sent to a user on registration

**Comment by ashay-maheshwari** [comment] 2016-12-15 09:16
Duplicate of #38

**Closed as completed by ashay-maheshwari** 2016-12-15 09:16 UTC
Labels: feature, in progress
