### ISSUE TITLE
Customizing edX platform 

### ISSUE THREAD

**Issue by ashay-maheshwari** [vlead/edx#12] opened 2016-04-18 12:00 UTC
There are different entities which comes configured with edX by default. We have to customize it so that edX platform looks specific to Virtual-labs. Following are the entities/components which are to be customized -
1.  Register page needs to be customized 
2.  Need to replace email address with example.com domain
3.  Need to fix the registration email
4.  Restricting a Student to login into studio and create/edit course
5.  Change the platform name in studio.
6.  Missing logo in studio home page
7.  Removing extra labels on edX from studio and other page
8.  Terms and conditions page of Studio signup page
9.  Need to change the placeholders in studio sign up page
10. Forgot password link in Studio signin page.
11. Footer and Header to match the current vlabs.ac.in landing page.
12. Start dates to be removed from each course tile.
13. Labs should replace Courses.
14. Color Theming ( match the current vlabs.ac.in)
15. All courses should be Anytime.
16. Consortium logos should be present like on https://www.edx.org/
17. lab tile outline specific for each institute

**Comment by travula** [comment] 2016-04-26 05:15
duplicate of #8

**Closed as completed by travula** 2016-04-26 05:15 UTC
Labels: duplicate
